### ISSUE TITLE
无法正常启动

### ISSUE THREAD

**Issue by sforman2861597** [koishi-nt/BetterQQNT#1]
![image](https://github.com/koishi-nt/BetterQQNT/assets/121373973/156bf981-a2c6-4bc4-857a-1619f5db48cb)
使用的better-qqnt.dll这个，名字改成了version.dll然后放qqnt安装目录了。
出现这个报错之后可以打开qq，但是插件没有生效，设置里找不到插件的设置，也没有之前版本的背景图

**Comment by sforman2861597** [comment]
上面那张图用的是better-qqnt.dll
然后换成那个better-qqnt-no-hijick.dll试了试
结果
![image](https://github.com/koishi-nt/BetterQQNT/assets/121373973/3c125864-8779-493a-8b85-af96b561bcb8)

**Comment by 15Shell** [comment]
相同情况
![168ea36a21846f250072072a68a2f74e](https://github.com/koishi-nt/BetterQQNT/assets/111548938/9183a959-e945-4fff-a797-37f67938e23d)

**Comment by MicroCBer** [comment]
请使用管理员权限打开
